on-unmatched = "info"

[formatter.nixfmt]
command = "nixfmt"
includes = [ "*.nix" ]

[formatter.deadnix]
command = "deadnix"
options = [ "--edit", "--no-lambda-arg", "--no-lambda-pattern-names" ]
includes = [ "*.nix" ]
